minimum_pre_commit_version: "3.7.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: black
        name: docker_black
        entry: docker compose exec -T glossary-app poetry run black .
        language: system
        pass_filenames: false

      - id: ruff
        name: docker_ruff
        entry: docker compose exec -T glossary-app poetry run ruff check --fix .
        language: system
        pass_filenames: false

      - id: mypy
        name: docker_mypy
        entry: docker compose exec -T glossary-app poetry run mypy --config-file pyproject.toml .
        language: system
        pass_filenames: false
