FROM python:3.12.1-slim

ENV http_proxy=http://10.0.20.6:80
ENV https_proxy=http://10.0.20.6:80
ENV POETRY_VERSION=2.0.1
ENV POETRY_HOME=/opt/poetry
ENV POETRY_VENV=/opt/poetry-venv
ENV POETRY_CACHE_DIR=/opt/.cache
ENV POETRY_VIRTUALENVS_CREATE=false
ENV TZ=Europe/Moscow

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl git \
    && rm -rf /var/lib/apt/lists/* \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime  \
    && echo $TZ > /etc/timezone

WORKDIR /backend

COPY poetry.lock pyproject.toml /backend/

RUN pip install poetry

RUN poetry install --no-root --no-interaction --without dev

ENV PYTHONPATH="/app:${PYTHONPATH}"

ENV http_proxy=""
ENV https_proxy=""
